package Views;

/**
 *
 * @author eancan
 */
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import models.ArriendoCuota;
import models.Cliente;
import storage.DataStorage;

public class Principal extends javax.swing.JFrame {

    private final DataStorage storage = DataStorage.getInstance();
    private final String DEFAULT_CLIENT_OPTION = "Seleccione Cliente";
    private final String DEFAULT_CAR_OPTION = "Seleccione Automovil";
    
    /**
     * Creates new form Clientes
     */
    public Principal() {
        initComponents();
        renderCmbClientes();
        renderCmbAutomovil();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jFrame1 = new javax.swing.JFrame();
        jMenu3 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jFrame2 = new javax.swing.JFrame();
        jFrame3 = new javax.swing.JFrame();
        panelPrincipal = new javax.swing.JTabbedPane();
        panelMenuPrincipal = new javax.swing.JPanel();
        txtPrecioPorDia = new javax.swing.JTextField();
        lblCantidadCuotas = new javax.swing.JLabel();
        txtCantidadCuotas = new javax.swing.JTextField();
        btnGuardarArriendoYMostrarCuotas = new javax.swing.JButton();
        scrlTablaCuotasAPagar = new javax.swing.JScrollPane();
        tblCuotasAPagar = new javax.swing.JTable();
        btnPagarPrimeraCuota = new javax.swing.JButton();
        txtMontoAPagar = new javax.swing.JTextField();
        cmbClientes = new javax.swing.JComboBox<>();
        lblTituloPanel1 = new javax.swing.JLabel();
        cmbCars = new javax.swing.JComboBox<>();
        lblFechaArriendo = new javax.swing.JLabel();
        txtFechaArriendo = new javax.swing.JTextField();
        lblDias = new javax.swing.JLabel();
        lblPrecioPorDia = new javax.swing.JLabel();
        lblMontoAPagar = new javax.swing.JLabel();
        txtDias = new javax.swing.JTextField();
        cmbShowAgregarCliente = new javax.swing.JButton();
        panelMenuClientes = new javax.swing.JPanel();
        lbl_P2_Clientes = new javax.swing.JLabel();
        lbl_P2_Cedula = new javax.swing.JLabel();
        lbl_P2_Nombre = new javax.swing.JLabel();
        txtCedulaCliente = new javax.swing.JTextField();
        txtNombreCliente = new javax.swing.JTextField();
        chkClienteVigente = new javax.swing.JCheckBox();
        btnAgregarCliente = new javax.swing.JButton();
        panelMenuPagoCuotas = new javax.swing.JPanel();
        btn_P3_mostrarPagosArriendo = new javax.swing.JButton();
        lbl_P3_seleccioneArriendo = new javax.swing.JLabel();
        lst_P3_seleccioneCliente = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        btn_P3_RealizarPago = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jMenu3.setText("jMenu3");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame3Layout = new javax.swing.GroupLayout(jFrame3.getContentPane());
        jFrame3.getContentPane().setLayout(jFrame3Layout);
        jFrame3Layout.setHorizontalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame3Layout.setVerticalGroup(
            jFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Semana 10 APP");

        lblCantidadCuotas.setText("Cantidad de cuotas");

        btnGuardarArriendoYMostrarCuotas.setText("Guardar arriendo y mostrar cuotas >>");
        btnGuardarArriendoYMostrarCuotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarArriendoYMostrarCuotasActionPerformed(evt);
            }
        });

        tblCuotasAPagar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Valor", "Pagada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrlTablaCuotasAPagar.setViewportView(tblCuotasAPagar);

        btnPagarPrimeraCuota.setLabel("Pagar Primera Cuota");
        btnPagarPrimeraCuota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarPrimeraCuotaActionPerformed(evt);
            }
        });

        txtMontoAPagar.setEditable(false);
        txtMontoAPagar.setToolTipText("");

        cmbClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Cliente" }));
        cmbClientes.setToolTipText("");
        cmbClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClientesActionPerformed(evt);
            }
        });

        lblTituloPanel1.setText("ARRIENDO CON CUOTAS");
        lblTituloPanel1.setMaximumSize(new java.awt.Dimension(122, 16));
        lblTituloPanel1.setMinimumSize(new java.awt.Dimension(122, 16));
        lblTituloPanel1.setPreferredSize(new java.awt.Dimension(122, 16));

        cmbCars.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Automovil" }));
        cmbCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCarsActionPerformed(evt);
            }
        });

        lblFechaArriendo.setText("Fecha de arriendo");

        txtFechaArriendo.setToolTipText("");

        lblDias.setText("Días");

        lblPrecioPorDia.setText("Precio por día");

        lblMontoAPagar.setText("Monto a pagar");

        cmbShowAgregarCliente.setText("Agregar Cliente");
        cmbShowAgregarCliente.setToolTipText("");
        cmbShowAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbShowAgregarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuPrincipalLayout = new javax.swing.GroupLayout(panelMenuPrincipal);
        panelMenuPrincipal.setLayout(panelMenuPrincipalLayout);
        panelMenuPrincipalLayout.setHorizontalGroup(
            panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                        .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDias)
                            .addComponent(lblFechaArriendo)
                            .addComponent(lblPrecioPorDia)
                            .addComponent(lblMontoAPagar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtDias, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFechaArriendo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecioPorDia)
                            .addComponent(txtMontoAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                                .addComponent(lblCantidadCuotas)
                                .addGap(18, 18, 18)
                                .addComponent(txtCantidadCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGuardarArriendoYMostrarCuotas))
                        .addGap(18, 18, 18)
                        .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPagarPrimeraCuota)
                            .addComponent(scrlTablaCuotasAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbShowAgregarCliente)
                            .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(cmbCars, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(95, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuPrincipalLayout.setVerticalGroup(
            panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                .addComponent(lblTituloPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(cmbShowAgregarCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuPrincipalLayout.createSequentialGroup()
                        .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechaArriendo)
                            .addComponent(txtFechaArriendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidadCuotas)
                            .addComponent(txtCantidadCuotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDias)
                            .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardarArriendoYMostrarCuotas))
                        .addGap(34, 34, 34)
                        .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecioPorDia)
                            .addComponent(txtPrecioPorDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelMenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMontoAPagar)
                            .addComponent(txtMontoAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scrlTablaCuotasAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(btnPagarPrimeraCuota)
                .addGap(49, 49, 49))
        );

        lblTituloPanel1.getAccessibleContext().setAccessibleDescription("");

        panelPrincipal.addTab("Arriendo Cuotas", panelMenuPrincipal);

        lbl_P2_Clientes.setText("CLIENTES");

        lbl_P2_Cedula.setText("Cédula:");

        lbl_P2_Nombre.setText("Nombre:");

        txtCedulaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaClienteActionPerformed(evt);
            }
        });

        chkClienteVigente.setText("Vigente?");
        chkClienteVigente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkClienteVigenteActionPerformed(evt);
            }
        });

        btnAgregarCliente.setText("Agregar Cliente");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuClientesLayout = new javax.swing.GroupLayout(panelMenuClientes);
        panelMenuClientes.setLayout(panelMenuClientesLayout);
        panelMenuClientesLayout.setHorizontalGroup(
            panelMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuClientesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMenuClientesLayout.createSequentialGroup()
                        .addGroup(panelMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_P2_Clientes)
                            .addComponent(lbl_P2_Nombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_P2_Cedula, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCedulaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(txtNombreCliente)))
                    .addGroup(panelMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkClienteVigente)
                        .addComponent(btnAgregarCliente)))
                .addContainerGap(553, Short.MAX_VALUE))
        );
        panelMenuClientesLayout.setVerticalGroup(
            panelMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuClientesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lbl_P2_Clientes)
                .addGap(43, 43, 43)
                .addGroup(panelMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_P2_Cedula)
                    .addComponent(txtCedulaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(panelMenuClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_P2_Nombre)
                    .addComponent(txtNombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(chkClienteVigente)
                .addGap(44, 44, 44)
                .addComponent(btnAgregarCliente)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        panelPrincipal.addTab("Clientes", panelMenuClientes);

        btn_P3_mostrarPagosArriendo.setText("Mostrar pagos arriendo seleccionado >>>");
        btn_P3_mostrarPagosArriendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_P3_mostrarPagosArriendoActionPerformed(evt);
            }
        });

        lbl_P3_seleccioneArriendo.setText("Seleccione arriendo:");

        lst_P3_seleccioneCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        btn_P3_RealizarPago.setText("Realizar Pago");

        jLabel12.setText("PAGOS");

        javax.swing.GroupLayout panelMenuPagoCuotasLayout = new javax.swing.GroupLayout(panelMenuPagoCuotas);
        panelMenuPagoCuotas.setLayout(panelMenuPagoCuotasLayout);
        panelMenuPagoCuotasLayout.setHorizontalGroup(
            panelMenuPagoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuPagoCuotasLayout.createSequentialGroup()
                .addGroup(panelMenuPagoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelMenuPagoCuotasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_P3_RealizarPago))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMenuPagoCuotasLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(lst_P3_seleccioneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMenuPagoCuotasLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(panelMenuPagoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMenuPagoCuotasLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btn_P3_mostrarPagosArriendo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                                .addComponent(jCheckBox1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMenuPagoCuotasLayout.createSequentialGroup()
                                .addComponent(lbl_P3_seleccioneArriendo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(98, 98, 98)))))
                .addGap(68, 68, 68))
        );
        panelMenuPagoCuotasLayout.setVerticalGroup(
            panelMenuPagoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuPagoCuotasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lst_P3_seleccioneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(panelMenuPagoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_P3_seleccioneArriendo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(panelMenuPagoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuPagoCuotasLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btn_P3_mostrarPagosArriendo))
                    .addGroup(panelMenuPagoCuotasLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuPagoCuotasLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelMenuPagoCuotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuPagoCuotasLayout.createSequentialGroup()
                                .addComponent(jCheckBox1)
                                .addGap(100, 100, 100)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_P3_RealizarPago)
                .addGap(6, 6, 6))
        );

        panelPrincipal.addTab("Pagar cuotas", panelMenuPagoCuotas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal))
        );

        panelPrincipal.getAccessibleContext().setAccessibleName("Menú principal");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClientesActionPerformed
        // TODO add yodsfur handling code here:
        System.out.println(cmbClientes.getSelectedItem());
        System.out.println(cmbClientes.getSelectedIndex());
    }//GEN-LAST:event_cmbClientesActionPerformed

    private void cmbCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCarsActionPerformed

    private void btnPagarPrimeraCuotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarPrimeraCuotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPagarPrimeraCuotaActionPerformed

    private void txtCedulaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaClienteActionPerformed

    private void btn_P3_mostrarPagosArriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_P3_mostrarPagosArriendoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_P3_mostrarPagosArriendoActionPerformed

    private void cmbShowAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbShowAgregarClienteActionPerformed
        panelPrincipal.setSelectedIndex(1);
    }//GEN-LAST:event_cmbShowAgregarClienteActionPerformed

    private void chkClienteVigenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkClienteVigenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkClienteVigenteActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        String cedula = txtCedulaCliente.getText().trim();
       
        if (cedula.isBlank()) {
            showError("Campo cedula no puede estar vacio");
            return;
        }
        
        String nombre = txtNombreCliente.getText().trim();
        if (nombre.isBlank()) {
            showError("Campo nombre no puede estar vacio");
            return;
        }
        
        if (storage.clienteExiste(cedula)) {
            showError("Ya existe un cliente registrado con numero de cedula ingreado");
            return;
        }
        
        Cliente cliente = new Cliente(cedula, nombre, chkClienteVigente.isSelected());
        storage.addClient(cliente);
        txtCedulaCliente.setText("");
        txtNombreCliente.setText("");
        chkClienteVigente.setSelected(false);
        renderCmbClientes();
        panelPrincipal.setSelectedIndex(0);
        showMessage( "Cliente registrado con exito");
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnGuardarArriendoYMostrarCuotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarArriendoYMostrarCuotasActionPerformed
        var selectedClient = (String)cmbClientes.getSelectedItem();
        if (DEFAULT_CLIENT_OPTION.equals(selectedClient)) {
            showError("Debe seleccionar un cliente");
            return;
        }
        
        var selectedCar = (String)cmbCars.getSelectedItem();
        if (DEFAULT_CAR_OPTION.equals(selectedCar)) {
            showError("Debe seleccionar un automovil");
            return;
        }
        
        int id = storage.getArriendoCuotaNextSeq();
        String fechaArriendo = txtFechaArriendo.getText().trim();
        int diasArriendo = getAsInt(txtDias);
        if (diasArriendo == -1) {
            showError("Dias arriendo debe ser numerico");
            return;
        }
        
        int cantidadCuotas = getAsInt(txtCantidadCuotas);
        if (cantidadCuotas == -1) {
            showError("Cantidad de cuotas debe ser numerico");
            return;
        }
        
        int precioPorDia = getAsInt(txtPrecioPorDia);
        if (precioPorDia == -1) {
            showError("Precio por dia debe ser numerico");
            return;
        }
        
        var cliente = storage.findClient(selectedClient.split(" ")[0]);
        var vehiculo = storage.findCar(selectedCar.split(" ")[0]);

        var arriendoCuota = new ArriendoCuota(id, fechaArriendo, diasArriendo, cliente, vehiculo, cantidadCuotas);
        
        if (!arriendoCuota.ingresarArriendoConCuota(precioPorDia)) {
            showError("La evaluacion no se ha completado correctamente.");
            return;
        }
        
        storage.addArriendoCuotaList(arriendoCuota);
        
        var cuotas = arriendoCuota.getCuotasArriendo();
        var tblModel = (DefaultTableModel) tblCuotasAPagar.getModel();
        tblModel.setRowCount(0);

        for (var cuota: cuotas) {
            var rowData = new Object[] { cuota.getNumCuota(), cuota.getValorCuota(), cuota.getPagada() };
            tblModel.addRow(rowData);
        }

        /*
        cmbClientes.setSelectedIndex(0);
        cmbCars.setSelectedIndex(0);
        txtFechaArriendo.setText("");
        txtDias.setText("");
        txtCantidadCuotas.setText("");
        txtPrecioPorDia.setText("");
        */
        renderCmbClientes();
        renderCmbAutomovil();
        txtMontoAPagar.setText(String.valueOf(arriendoCuota.obtenerMontoAPagar(precioPorDia)));
        showMessage("Arriendo coutas guardado correctamente");
    }//GEN-LAST:event_btnGuardarArriendoYMostrarCuotasActionPerformed
    
    private int getAsInt(JTextField field) {
        try {
            var value = field.getText().trim();
            System.out.println("value: " + value);
            return Integer.parseInt(value);
        } catch(Exception e){
            System.out.println("Error: " + e.getMessage());
            return -1;
        }
    }

    private void renderCmbClientes() {
        var items = storage.getClientes().stream()
            .map(c -> c.getCedula() + " - " + c.getNombre() +  " - " + (c.isVigente() ?  "Vigente" : " No Vigente"))
            .toList();
        var options = new ArrayList<String>();
        options.add(DEFAULT_CLIENT_OPTION);
        options.addAll(items);
        cmbClientes.setModel(new DefaultComboBoxModel<>(options.toArray(String[]::new)));
    }
    
    private void renderCmbAutomovil() {
        var items = storage.getVehiculos().stream()
                .map(v -> v.getPatente()+ " - " + v.getCondicion())
                .toList();
        var options = new ArrayList<String>();
        options.add(DEFAULT_CAR_OPTION);
        options.addAll(items);
        cmbCars.setModel(new DefaultComboBoxModel<>(options.toArray(String[]::new)));
    }
    
    protected void showError(String message) {
        JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    protected void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message, "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnGuardarArriendoYMostrarCuotas;
    private javax.swing.JButton btnPagarPrimeraCuota;
    private javax.swing.JButton btn_P3_RealizarPago;
    private javax.swing.JButton btn_P3_mostrarPagosArriendo;
    private javax.swing.JCheckBox chkClienteVigente;
    private javax.swing.JComboBox<String> cmbCars;
    private javax.swing.JComboBox<String> cmbClientes;
    private javax.swing.JButton cmbShowAgregarCliente;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JFrame jFrame3;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JList<String> jList1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblCantidadCuotas;
    private javax.swing.JLabel lblDias;
    private javax.swing.JLabel lblFechaArriendo;
    private javax.swing.JLabel lblMontoAPagar;
    private javax.swing.JLabel lblPrecioPorDia;
    private javax.swing.JLabel lblTituloPanel1;
    private javax.swing.JLabel lbl_P2_Cedula;
    private javax.swing.JLabel lbl_P2_Clientes;
    private javax.swing.JLabel lbl_P2_Nombre;
    private javax.swing.JLabel lbl_P3_seleccioneArriendo;
    private javax.swing.JComboBox<String> lst_P3_seleccioneCliente;
    private javax.swing.JPanel panelMenuClientes;
    private javax.swing.JPanel panelMenuPagoCuotas;
    private javax.swing.JPanel panelMenuPrincipal;
    private javax.swing.JTabbedPane panelPrincipal;
    private javax.swing.JScrollPane scrlTablaCuotasAPagar;
    private javax.swing.JTable tblCuotasAPagar;
    private javax.swing.JTextField txtCantidadCuotas;
    private javax.swing.JTextField txtCedulaCliente;
    private javax.swing.JTextField txtDias;
    private javax.swing.JTextField txtFechaArriendo;
    private javax.swing.JTextField txtMontoAPagar;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPrecioPorDia;
    // End of variables declaration//GEN-END:variables
}
